// Code generated by ogen, DO NOT EDIT.

package policeuk

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetDatasetAvailability implements getDatasetAvailability operation.
	//
	// Get a list of available datasets by date and police force.
	//
	// GET /crimes-street-dates
	GetDatasetAvailability(ctx context.Context) (DatasourceAvailability, error)
	// GetPoliceForce implements getPoliceForce operation.
	//
	// Get detailed information about a specific police force.
	//
	// GET /forces/{forceId}
	GetPoliceForce(ctx context.Context, params GetPoliceForceParams) (GetPoliceForceRes, error)
	// ListPoliceForces implements listPoliceForces operation.
	//
	// List all of the police forces available within the data.police.uk dataset.
	//
	// GET /forces
	ListPoliceForces(ctx context.Context) (PoliceForces, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
