// Code generated by ogen, DO NOT EDIT.

package policeuk

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetPoliceForceParams is parameters of getPoliceForce operation.
type GetPoliceForceParams struct {
	// ID of the police force to fetch information about.
	ForceId PoliceForceId
}

func unpackGetPoliceForceParams(packed middleware.Parameters) (params GetPoliceForceParams) {
	{
		key := middleware.ParameterKey{
			Name: "forceId",
			In:   "path",
		}
		params.ForceId = packed[key].(PoliceForceId)
	}
	return params
}

func decodeGetPoliceForceParams(args [1]string, argsEscaped bool, r *http.Request) (params GetPoliceForceParams, _ error) {
	// Decode path: forceId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "forceId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				var paramsDotForceIdVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotForceIdVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.ForceId = PoliceForceId(paramsDotForceIdVal)
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "forceId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
