// Code generated by ogen, DO NOT EDIT.

package policeuk

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ListDatasetAvailability implements listDatasetAvailability operation.
//
// Get a list of available datasets by date and police force.
//
// GET /crimes-street-dates
func (UnimplementedHandler) ListDatasetAvailability(ctx context.Context) (r DatasourceAvailability, _ error) {
	return r, ht.ErrNotImplemented
}
